### ISSUE TITLE
Font Mastering

### ISSUE THREAD

**Issue by vv-monsalve** [googlefonts/alumni#2]
**Diacritics**
- [x] Composite glyphs need to be made out of components using anchors
- [x] Comb.case are missing
- [x] Misaligned diacritics
- [x] Create caron.alt and adjust Lcaron, lcaron, dcaron, tcaron 

**Glyphs**
- [x] Missing glyphs: 0x00A0 (NO-BREAK SPACE), 0x00AD (SOFT HYPHEN), 0x2074 (SUPERSCRIPT FOUR) and 0x2215 (DIVISION SLASH)
- [ ] Add extreme points
- [ ] Correct path direction (command)

**OT Features**
- [x] Ensure the OT features include everything and are working well (e.g. fi fl included)

**Comment by vv-monsalve** [comment]
Hi @crystaltype, please when working on stacked diacs in Alumni also check the composite glyphs for Cyrilic in the Roman file.

**Comment by crystaltype** [comment]
Roger that, tasks remaining:

- [x] Check cyrillic in the roman masters
- [x] Adjust anchor position for hook above
- [x] Create comb.case for stacked diacritics with the same weight but smaller by 30% to avoid vertical metrics problems and to be more elegant in heavy weights mainly used for display use.
- [x] Adjust stacked diacritics positions and weight.
- [x] Adjust horncomb position to avoid overlapping on specific Vietnamese kerning pairs.
- [x] check ydotbelow diacritic position
- [x] Perform the same task for italic masters
