### ISSUE TITLE
Browser Preview

### ISSUE THREAD

**Issue by vv-monsalve** [googlefonts/alumni#5]
Alumni seems to have some issues when testing it with template 2 for Vietnamese. It is displaying it wrongly in some browsers like Edge or Firefox. Despite the preview for Safari, it is working well when opening the `html` in my local browser (`Version 12.1.2 (14607.3.9)` on Mojave)

Below there are the first images produced by BrowserStack when using `gen-html proof`. In the additional comments are some pics taken for the same `.html` files opening them directly in Windows environments.

The Unicodes IDs are ok and are the same used in other projects like [Glory](https://github.com/googlefonts/glory/issues/7#issuecomment-861593674) which isn't reporting any Issue.

### Text

**OS X High Sierra Safari_11**
![Desktop_OS_X_High_Sierra_safari_11 1_](https://user-images.githubusercontent.com/48698976/121458663-67811e00-c96f-11eb-9fff-9bdab51681fc.png)
**Windows 10 Chrome_71**
![Desktop_Windows_10_chrome_71 0_](https://user-images.githubusercontent.com/48698976/121458668-68b24b00-c96f-11eb-8b43-64faaae52a97.png)
**Windows 10 Edge_18**
![Desktop_Windows_10_edge_18 0_](https://user-images.githubusercontent.com/48698976/121458661-664ff100-c96f-11eb-9ad7-098d12f65b9a.png)

**Comment by vv-monsalve** [comment]
Other proof images. It seems something is going wrong with the Vietnamese-2.html template text in Firefox in Windows.

Images taken under `Linux debian`

### **Chrome**
`Version 88.0.4324.96`

![ChromeVietnamese](https://user-images.githubusercontent.com/48698976/121463136-14ab6480-c977-11eb-9ea2-9e53a6705ce7.jpg)
![ChromeVietnamese2](https://user-images.githubusercontent.com/48698976/121463145-170dbe80-c977-11eb-9589-d35af3088751.jpg)

Glyphs
![ChromeGlyphs](https://user-images.githubusercontent.com/48698976/121706747-88df2880-ca9b-11eb-9b39-f43de06fe581.jpg)


------

### **Firefox**
`Version 78`

![FirefoxVietnamese2](https://user-images.githubusercontent.com/48698976/121463297-6f44c080-c977-11eb-9c36-fb513ed2a58b.jpg)
![Firefox-Vietnamese](https://user-images.githubusercontent.com/48698976/121463267-5f2ce100-c977-11eb-9396-a81ecfbb0d81.jpg)

Glyphs
![FirefoxGlyphs](https://user-images.githubusercontent.com/48698976/121706713-8086ed80-ca9b-11eb-963f-3c8ba95e68de.jpg)



------

### **Navegador Web Browser**

`Version 5.3.0.34`

![NavegadorWebBroserVietnamese](https://user-images.githubusercontent.com/48698976/121706548-59c8b700-ca9b-11eb-8647-621b8dd826d4.jpg)
![NavegadorWebBrowserVietnamese2](https://user-images.githubusercontent.com/48698976/121463677-188bb680-c978-11eb-9973-a8960fa3e0d7.jpg)

Glyphs
![NavegadorWebBrowserGlyphs](https://user-images.githubusercontent.com/48698976/121463674-175a8980-c978-11eb-8f14-d6e01492b1ae.jpg)

**Comment by vv-monsalve** [comment]
New tests performed by Nhung on Windows.
@crystaltype Please specify the Operative System and the version number of the browsers. Thanks

**Firefox**

![alumni-Nhung-Firefox](https://user-images.githubusercontent.com/48698976/121706891-aad8ab00-ca9b-11eb-946c-45950dc58e89.png)
![alumni-Nhung-Firefox-detail](https://user-images.githubusercontent.com/48698976/121706918-b0ce8c00-ca9b-11eb-8c70-2b41bc389534.png)

**Edge**
![alumni-Nhung-edge](https://user-images.githubusercontent.com/48698976/121707176-ee331980-ca9b-11eb-9a45-9c912ff034a7.png)

**Comment by crystaltype** [comment]
Hello,
Here are version number of the browsers: 
Edge Version 91.0.864.48 (Official build) (64-bit) on Windows 10
Firefox 89.0 on Windows 10

**Comment by vv-monsalve** [comment]
Two marks didn't have the proper Unicode ID, and so the Browsers that don't use the precomposed glyphs in the font didn't create the accented marks ok.
