### ISSUE TITLE
Macron position

### ISSUE THREAD

**Issue by vv-monsalve** [googlefonts/alumni#7]
Hi @crystaltype, after running diff browsers for the Update, I noticed the `macroncomb` position in the roman source had changed. I restored it to its original position but the stacked diacritics need to be reviewed now.

Please take the latest source in the `qaAlumniPlus` branch to inspect it. Thanks

**OS X High Sierra Safari_11**
![Desktop_OS_X_High_Sierra_safari_11 1_](https://user-images.githubusercontent.com/48698976/145064259-9f037ceb-836f-4b50-af3d-8044b04406f1.gif)
**Windows 10 Chrome_71**
![Desktop_Windows_10_chrome_71 0_](https://user-images.githubusercontent.com/48698976/145064284-d4c28bc2-ed94-44fe-9c07-c2a5fb56e325.gif)
**Windows 10 Edge_18**
![Desktop_Windows_10_edge_18 0_](https://user-images.githubusercontent.com/48698976/145064287-de208613-cf4a-4eb9-9b01-ed1f832ea7a2.gif)

**Comment by crystaltype** [comment]
Hi @vv-monsalve , thank you, I've fixed it and pushed new sources.
